name:                tucker
version:             0.1.0.0
github:              "rod-lin/tucker"
license:             MIT
author:              "Rod Lin"
maintainer:          "rod.yeti@outlook.com"
copyright:           "2018 Rod"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/rod-lin/tucker>

dependencies:
- base >= 4.7 && < 5
- largeword
- bytestring
- stm
- strict-io
- time
- monad-loops
- network
- leveldb-haskell
- filepath
- directory
- mmorph
- resourcet
- hex
- random
- HUnit
- unbounded-delays
- cryptonite
- memory
- asn1-encoding
- asn1-types
- containers
- ordered-containers
- concurrent-extra
- regex-posix
- mtl
- split
- arithmoi
- transformers
- exceptions
- ansi-terminal
- binary
- cpu
- unix

library:
  source-dirs: src

executables:
  tucker-exe:
    c-sources:
    - chash/mine.c
    - chash/sha256.c
    - chash/hash256.c

    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optc-O3
    dependencies:
    - tucker

# tests:
#   tucker-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - tucker
